[package]
name = "boolify"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "boolify"
path = "src/cli.rs"

[dependencies]
bristol-circuit = { git = "https://github.com/voltrevo/bristol-circuit", rev = "2a8b001" }
serde = "1.0"
serde_json = "1.0"
