[package]
name = "boolify"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "boolify"
path = "src/cli.rs"

[dependencies]
bristol-circuit = { git = "https://github.com/cedoor/bristol-circuit", rev = "ff7587a" }
serde = "1.0"
serde_json = "1.0"
